### ISSUE TITLE
Create dedicated, public QR generating API endpoint

### ISSUE THREAD

**Issue by santiesque** [formsend/nano#11]
I think the Checkout API and the world would benefit from Nano.to having a separate, public QR generating API endpoint.

Something like this:

```
GET: https://api.nano.to/qr?address=nano_37...&color=red&icon=nano
```
Etc.

Discussions welcomed.

**Comment by dderooy** [comment]
Azure functions (or lambda) would be perfect for this. A function could make QR pic and then upload to CDN. If no CDN, its a relatively small pic so you might be able to get away with returning base64 directly.

**Comment by santiesque** [comment]
Good point. 

Call me old fashion, but indeed, the base64 or (Buffer) would be small. I'd store in-memory and served from there :) 

Cloud function cold start can't compete with in-memory :)

**Comment by zQueal** [comment]
Exceptionally easy to implement using a recursive API call to the Google Chart API:

    https://chart.apis.google.com/chart?cht=qr&chs=200x200&chld=L|0&chl=nano_19ditzdezoffa3g8hjpcoqb6c6q5zjq13u1coqtzrwh9wm6e8j4zeom3i5gw

Scans just fine in Natrium.
