### ISSUE TITLE
Utility convert does not throw errors instead returns

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [formsend/nano#28]
Hi there,

I was inspecting the source code and I see that Errors are returned rather than `throw`. Can I learn the reason why? I see that you are using `try` and `catch`, but there is a little good reason for doing that. Throwing right in the error will mitigate problems later on.

For example, if you are planning to make use of the test suite (I just started to write some of them), watching `throw`s is easier than looking at return values.

I would like to hear your thoughts on that.

**Comment by BerkhanBerkdemir** [comment]
Are you planning to rewrite the converter interface? I would like to try my chance.

**Comment by santiesque** [comment]
> Are you planning to rewrite the converter interface? I would like to try my chance.

Haha! Have at it!

**Comment by BerkhanBerkdemir** [comment]
> > Are you planning to rewrite the converter interface? I would like to try my chance.
> 
> Haha! Have at it!

Hi @santiesque,

I am done with experimenting new Converter interface and I want to share it with you. I didn't want to create PR because that will add another overhead for you, but you can take a look at it in my repository in [`rewrite-of-converter-library`](https://github.com/BerkhanBerkdemir/nano/tree/rewrite-of-converter-library). I would like to hear your thoughts before making a PR :smiley:

**Comment by santiesque** [comment]
Indeed I have a lot going on! 

Just seeing your branch! Will check. Looks good!
