### ISSUE TITLE
Changing out NANOCRAWLER button for NANOLOOKER

### ISSUE THREAD

**Issue by santiesque** [formsend/nano#34]
NanoLooker is better looking. 

Nanocrawler still reliable AF tho. Nothing personal.

Thoughts? Will go into effect next week.

**Comment by BerkhanBerkdemir** [comment]
I would say nanocrawler is widely used and really don't know the main reason. nanolooker is a great project as well. I wouldn't mind using it. For me, the only reason I have :+1: for nanolooker is the nanocrawler's UI is not saying the questions I have in my mind in miliseconds. I know this is a minor thing but it is there.

**Comment by santiesque** [comment]
Indeed. 

I've done my best to 'simplify' Nano.to to provide the essential information. While providing a Third Party link heavy on information. 

Look at the Hash Ednpoint on Nano.to For Example: 

https://api.nano.to/hash/A341FBD3942B411D98BAC16241E5BC149DBE0D54D9BB23A873BC2A2C2B92B113

<img width="615" alt="Screen Shot 2021-11-07 at 11 43 20 AM" src="https://user-images.githubusercontent.com/9022456/140653886-194a604c-db40-43c4-9c4d-16053a52b648.png">

Clean
