### ISSUE TITLE
Waiting on NANO node to sync. Back online in 24 hrs.

### ISSUE THREAD

**Issue by santiesque** [formsend/nano#37]
My first born Nano node. 🥲 

US-1 (New York, New York)

https://us-1.nano.to/

No RPC access. It's for Nano.to.

**Comment by zQueal** [comment]
Wallet address for the representative isn't open. I suggest sending an opening transaction to it, and receiving.

**Comment by santiesque** [comment]
@zQueal  Thanks!

It was having issues syncing. Fast sync did not work because the NanoNinja 7z Dump was from last month. The Node got hung at 97.2% sync for days. 

Just 'fast sycned' using the Ledger from Official NANO Discord chat.

Hoping that does the trick.
