### ISSUE TITLE
Correct qr code content

### ISSUE THREAD

**Issue by ArTombado** [formsend/nano#4]
Current qr codes are showing an amount in decimal(ex: 1.844997), but natrium and nault only accept this amount in raw(ex: 1844997000000000000000000000000). Also, to put the nano account it needs to put "nano:" before the address.

❌nano_37y6iq8m1zx9inwkkcgqh34kqsihzpjfwgp9jir8xpb9jrcwhkmoxpo61f4o?amount=1.844997
✔️nano:nano_37y6iq8m1zx9inwkkcgqh34kqsihzpjfwgp9jir8xpb9jrcwhkmoxpo61f4o?amount=1844997000000000000000000000000

**Comment by santiesque** [comment]
Oh man... Good stuff.

I wonder if Trust Wallet (the wallet i use) supports:

```
nano:nano_37y6iq8m1zx9inwkkcgqh34kqsihzpjfwgp9jir8xpb9jrcwhkmoxpo61f4o?amount=1844997000000000000000000000000
```

**Comment by ArTombado** [comment]
> I wonder if Trust Wallet (the wallet i use) supports:
> 
> ```
> nano:nano_37y6iq8m1zx9inwkkcgqh34kqsihzpjfwgp9jir8xpb9jrcwhkmoxpo61f4o?amount=1844997000000000000000000000000
> ```

I didn't know that trust wallet uses a different format! Maybe we can ask they to use the other format?

**Comment by santiesque** [comment]
I may have to use two different QR Codes for this.

Trust wallet uses decimal & natrium uses RAW. Not sure about other wallerts.

**Comment by filipesmedeiros** [comment]
I've been through this problem, and the only solution I could come up with is to let the user choose which QR they want (maybe a dropdown or just all of them side by side?)

Either way, if you're gonna have a default one, let's make it the standar one (the one OP suggested)

Reference:
https://docs.nano.org/integration-guides/the-basics/#uri-and-qr-code-standards

**Comment by santiesque** [comment]
Agreed. 

Ok, this will be more a UI challenge, than a logic one. 

I'll drop some example screens here in a few days, for thoughts.

**Comment by santiesque** [comment]
A little progress on this.

If you want to force the API to use RAW when generating QR Code here's a new flag (param)

```
?raw=true
```

Example: 
```
https://nano.to/moon?raw=true
```

**Comment by ArTombado** [comment]
Nice work! :D

**Comment by santiesque** [comment]
F*ck it. Natrium support is now default.

Trust Wallet is NOT using the specs. If you want Trust Wallet QR codes, use 'raw=false' URL or BODY param.
