### ISSUE TITLE
Incorrect link to QR code docs

### ISSUE THREAD

**Issue by keerifox** [formsend/nano#50]
https://nano.to/keeri/qrcode?browser=true

incorrect:
https://github.com/formsend/nano/blob/main/examples/qrcode-examples.md

correct:
https://github.com/formsend/nano/blob/main/docs/001-qrcode-examples.md

**Comment by santiesque** [comment]
Pull Request, pls :)

**Comment by keerifox** [comment]
@santiesque didn't have time to do it at the time, don't see it anywhere in the repo

**Comment by santiesque** [comment]
Me neither. Add it :)

**Comment by keerifox** [comment]
@santiesque you're the one with the source code for it
