### ISSUE TITLE
API No Longer Respects Amount

### ISSUE THREAD

**Issue by zQueal** [formsend/nano#52]
> ht -b https://nano.to/pay/xanza amount==5000000000000000000000000000000

![M1VYkMp](https://user-images.githubusercontent.com/239193/148163320-349fd8a0-66e1-4b77-bb56-ff980efa112b.png)

Have also tried whole numbers, and not raw. Nothing is respected. There's also seems to be a bug with the username where extra characters are added for no reason.

**Comment by santiesque** [comment]
The API may have changed. Sorry.

These work for me: https://nano.to/pay/xanza?price=500

And this is the same: https://nano.to/pay/xanza?amount=500

Amount is in USD at the moment, not NANO... I know, I know.

**Comment by zQueal** [comment]
That must have been my confusion. Copy that, thanks.
