### ISSUE TITLE
[Bug] Customize Checkout Page Currency

### ISSUE THREAD

**Issue by Legolaszstudio** [formsend/nano#53]
If you send a request like this:
`https://nano.to/Moon?currency=HUF`

The documentation doesn't mention anything about being able to pass currency value, but if you do then you will get some weird results;
![](https://i.imgur.com/d40vTWp.png)

As you can see `HUF` appears multiple times, but the conversion rate is still `USD`, which is very misleading as `1$=310Ft`.

I would be really grateful if you could add a feature to select a currency when creating a checkout page. If you do, then maybe I will drop a few NANOs in your wallet as a reward ;)

**Comment by bingland** [comment]
I was playing around with the nano.to checkout page today and noticed this as well. 

I would volunteer to fix it however it appears that the code for the checkout stuff and also the front end API is not located on this repo, it seems that this repo is just for the backend API. Which is a bit confusing to me 🤔 That being said though, I'd gladly work on something like this if I could access the actual repo and contribute :)

**Comment by bingland** [comment]
I was playing with nano.to the other day and I noticed this too. @santiesque I'll be glad to fix bugs like this however it appears that the front end API and checkout pages aren't on public repos, is this correct?

**Comment by santiesque** [comment]
- Multi-currency support is coming. But not polished. That's why it kinda works. 

> the front end API and checkout pages aren't on public repos

At the time of this writing, Nano.to is closed-source. This public repo currently hosts an NPM package. That we use for talking to the Nano Node. Plans for open sourcing Nano.to entirely are in the works.
